### ISSUE TITLE
KeyError: 'hits'

### ISSUE THREAD

**Issue by Bluscream** [Senth/minecraft-mod-manager#196]
### Describe the bug 
Python exception thrown.

### Steps to reproduce
[mmm.exe.txt](https://github.com/Senth/minecraft-mod-manager/files/9229513/mmm.exe.txt)<details>
<summary>Logs</summary>

```shell
CurseForge has been disabled! See https://github.com/Senth/minecraft_mod_manager for more information.
Found fabric mod: altoclef-0.4.1a (Alto Clef) [fabric]
Found fabric mod: architectury-4.6.77 (Architectury) [fabric]
Found fabric mod: betterf3-1.3.2 (BetterF3) [fabric]
Found fabric mod: betterpingdisplay-1.1.1 (Better Ping Display) [fabric]
Found fabric mod: bobby-4.0.0 (Bobby) [fabric]
Found fabric mod: chesttracker-1.1.16 (Chest Tracker) [fabric]
Found fabric mod: cloth-api-3.2.64 (Cloth API) [fabric]
Found fabric mod: cloth-config-8.0.75 (Cloth Config v8) [fabric]
Found forge mod: cloth_config-8.0.75 (Cloth Config v8 API) [forge]
Found fabric mod: clumps-8.0.0+10 (Clumps) [fabric]
Found fabric mod: continuity-2.0.0+1.19 (Continuity) [fabric]
Found fabric mod: enhancedblockentities-0.6+1.18.2 (Enhanced Block Entities) [fabric]
Found fabric mod: entityculling-1.5.2-mc1.19 (EntityCulling-Fabric) [fabric]
Found fabric mod: fabric-0.58.5+1.19.1 (Fabric API) [fabric]
Found fabric mod: ferritecore-4.2.1 (FerriteCore) [fabric]
Found fabric mod: fpsreducer-1.18.2-2.0 (FPS Reducer) [fabric]
Found fabric mod: indium-1.0.6+mc1.19 (Indium) [fabric]
Found fabric mod: inventoryhud-3.4.2 (Inventory HUD +) [fabric]
Found fabric mod: inventorytabs-0.9.beta-1.18.x (Inventory Tabs) [fabric]
Found fabric mod: iris-1.2.6 (Iris) [fabric]
Found fabric mod: lambdabettergrass-1.3.0+1.19 (LambdaBetterGrass) [fabric]
Found fabric mod: lambdynlights-2.1.2+1.19 (LambDynamicLights) [fabric]
Found fabric mod: lazydfu-0.1.3 (LazyDFU) [fabric]
Found fabric mod: litematica-0.11.3 (Litematica) [fabric]
Found fabric mod: lithium-0.8.3 (Lithium) [fabric]
Found fabric mod: malilib-0.12.1 (MaLiLib) [fabric]
Found fabric mod: meteor-client-0.4.9 (Meteor Client) [fabric]
Found fabric mod: modmenu-4.0.5 (Mod Menu) [fabric]
Found fabric mod: not-enough-servers-1.0.2 (Not Enough Servers) [fabric]
Found fabric mod: recipecache-0.2.1-1.17.1 (recipecache) [fabric]
Found fabric mod: roughlyenoughitems-8.3.510 (Roughly Enough Items) [fabric]
Found fabric mod: roughlyenoughprofessions-1.0.1 (Roughly Enough Professions) [fabric]
Found fabric mod: sodium-0.4.2+build.16 (Sodium) [fabric]
Found fabric mod: starlight-1.1.1+fabric.ae22326 (Starlight) [fabric]
Found fabric mod: viafabric-0.4.7+5-main (ViaFabric) [fabric]
Found fabric mod: xaeroworldmap-1.26.1 (Xaero's World Map) [fabric]
Found fabric mod: xaerominimap-22.12.0 (Xaero's Minimap) [fabric]
xaerominimap
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word:
    🔺 Mod not found on any site...
xaeroworldmap
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word:
    🔺 Mod not found on any site...
viafabric
    🔍 Searching for mod
        🔍 Searching for viafabric on Sites.modrinth
        🟢 Found viafabric on Sites.modrinth
    ⬇ Downloading...
    🟢 Updated 0.4.7+5-main -> 0.4.8+13-main
starlight
    🔍 Searching for mod
        🔍 Searching for starlight on Sites.modrinth
        🟢 Found starlight on Sites.modrinth
    ⬇ Downloading...
    🟢 Updated 1.1.1+fabric.ae22326 -> 1.0.2+fabric.89b8d9f
sodium
    🔍 Searching for mod
        🔍 Searching for sodium on Sites.modrinth
        🟢 Found sodium on Sites.modrinth
    ⬇ Downloading...
    🟢 Updated 0.4.2+build.16 -> 0.4.1+build.15
roughlyenoughprofessions
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word: roughly enough professions
    🔺 Mod not found on any site...
roughlyenoughitems
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word: roughly enough items
    🔺 Mod not found on any site...
recipecache
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word: recipe cache
    🔺 Mod not found on any site...
not-enough-servers
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
    🔺 Mod not found on any site...
modmenu
    🔍 Searching for mod
        🔍 Searching for modmenu on Sites.modrinth
        🟢 Found modmenu on Sites.modrinth
    ⬇ Downloading...
    🟢 Updated 4.0.5 -> 3.2.3
meteor-client
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
    🔺 Mod not found on any site...
malilib
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
        🔍 Searching on Sites.modrinth by splitting word: Mali lib
    🔺 Mod not found on any site...
lithium
    🔍 Searching for mod
        🔍 Searching for lithium on Sites.modrinth
        🟢 Found lithium on Sites.modrinth
    ⬇ Downloading...
    🟢 Updated 0.8.3 -> 0.7.10
litematica
    🔍 Searching for mod
        🔍 Searching on Sites.modrinth
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\Scripts\mmm.exe\__main__.py", line 7, in <module>
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\__main__.py", line 42, in main
    update.execute(config.arg_mods)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\app\update\update.py", line31, in execute
    self.find_download_and_install(mods_to_update)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\app\download\download.py", line 35, in find_download_and_install
    mod.sites = self._finder.find_mod(mod)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\gateways\api\mod_finder.py", line 62, in find_mod
    infos = api.search_mod(possible_name)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\gateways\api\modrinth_api.py", line 53, in search_mod
    mods = self._search_mod(search)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\blusc\AppData\Roaming\Python\Python311\site-packages\minecraft_mod_manager\gateways\api\modrinth_api.py", line 73, in _search_mod
    for mod_info in json["hits"]:
                    ~~~~^^^^^^^^
KeyError: 'hits'

[process exited with code 1 (0x00000001)]
```
</details>

### Info
 - OS: Win11
 - Python --version: Python 3.10.5
 - minecraft-mod-manager --version: minecraft-mod-manager: 1.4.0

**Comment by Senth** [comment]
Thanks for reporting, when searching for litematica it seems to be missing hits. This can probably be fixed easily quite soon

**Comment by Senth** [comment]
Ahh, you already added a fix for it. Thanks 😁
