### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by tokenspins** [Senth/minecraft-mod-manager#29]
When i try to use minecraft-mod-manager it gives me the following error:

> Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2544.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\xmb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\Scripts\minecraft-mod-manager.exe\__main__.py", line 4, in <module>
  File "C:\Users\xmb\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\minecraft_mod_manager\__main__.py", line 1, in <module>
    from .adapters.repo_impl import RepoImpl
ModuleNotFoundError: No module named 'minecraft_mod_manager.adapters'

System: Windows 10 Build 19042.928
Python: version 3.8.9

**Comment by bennett-zhang** [comment]
I'm getting the same error.

**Comment by Senth** [comment]
Will check on it later today 🙂

**Comment by Senth** [comment]
Should work now, after doing some changes to the setup-process it didn't include everything when releasing a package. So it worked when checking out the repository, but not when installing from pip.
