### ISSUE TITLE
Error with Item Model Fix

### ISSUE THREAD

**Issue by itsmeboy0** [Senth/minecraft-mod-manager#53]
Crashes when you list with [Item Model Fix](https://www.curseforge.com/minecraft/mc-mods/item-model-fix) installed.

To reproduce:
```
minecraft-mod-manager install item-model-fix
minecraft-mod-manager list
```

Error:
```
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\minecraft-mod-manager.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\minecraft_mod_manager\__main__.py", line 21, in main
    repo = RepoImpl(jar_parser, sqlite, downloader)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\adapters\repo_impl.py", line 26, in __init__
    self.mods = self.db.sync_with_dir(jar_parser.mods)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\jar_parser.py", line 30, in mods
    mod = JarParser.get_mod_info(file)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\jar_parser.py", line 42, in get_mod_info
    mod = JarParser._parse_fabric(zip)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\jar_parser.py", line 60, in _parse_fabric
    object = json.load(json_file)
  File "c:\python39\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
  File "c:\python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "c:\python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 7 column 55 (char 153)
```

**Comment by Senth** [comment]
Hi @itsmeboy0,

Thanks a bunch for all the bug reporting 😃 It helps a lot when someone else tries it and finds bugs 🙂 

I'm working on another project that takes some time, but I'll see if I can squeeze in some programming either this weekend or the next to fix the easier bugs 🙂
