### ISSUE TITLE
Does not remove old jar file if mod is updated

### ISSUE THREAD

**Issue by itsmeboy0** [Senth/minecraft-mod-manager#54]
Additionally, I could not list my mods afterward because of the duplicate files:
```
Traceback (most recent call last):
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\sqlite.py", line 138, in insert_mod
    self._connection.execute(
sqlite3.IntegrityError: UNIQUE constraint failed: mod.id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\minecraft-mod-manager.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\minecraft_mod_manager\__main__.py", line 21, in main
    repo = RepoImpl(jar_parser, sqlite, downloader)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\adapters\repo_impl.py", line 26, in __init__
    self.mods = self.db.sync_with_dir(jar_parser.mods)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\sqlite.py", line 65, in sync_with_dir
    self.insert_mod(mod)
  File "c:\python39\lib\site-packages\minecraft_mod_manager\gateways\sqlite.py", line 151, in insert_mod
    raise ModAlreadyExists(mod)
minecraft_mod_manager.core.errors.mod_already_exists.ModAlreadyExists: Mod architectury already found in the the db.
```

**Comment by Senth** [comment]
Good catch, it probably shouldn't fail if there are two mods with the same ID (but different versions). I'll create a follow-up issue to improve that functionality.
